# Mini Projeto Avaliativo - Análises de  (AED)
### Base Varejo
#### Aluno: Anildo Santos Turma: Análises de dados com Python T3

In [59]:
# importando Biblioteca
import pandas as pd

In [60]:
# Criando DataFrame
# Ao abrir Os arquivos vir que são separados por ponto e vírgula e não somente por vírgula
# utilizei o sep=";" e se tiver acentos o encording="utf-8" vai garantir que sejam lidos corretamente.

df = pd.read_csv("Base Varejo.csv",sep=";",encoding="utf-8")

df

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [ ]:
# Verificando como cada Dado analisado se encontra para as devidas correções.
df.dtypes

DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

# Analisando a Tabela

In [62]:
# Pecorre toda minha tabela e verifica onde há valores nulos e vazios , e me mostra a quantidade os somando

df.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [63]:
# Verificando quantas linhas duplicadas há no arquivo e me mostra a quantidade

print("Linhas_Duplicadas" , df.duplicated().sum)

Linhas_Duplicadas <bound method Series.sum of 0         False
1         False
2         False
3         False
4         False
          ...
829995     True
829996     True
829997     True
829998    False
829999    False
Length: 830000, dtype: bool>

In [64]:
# Verificando se há produtos com categoria vazia, onde ela tava usando o #N/D como um nulo desfarçado

print("Produtos_vazios (#N/D):", (df["PR_CAT"]=="#N/D").sum())

Produtos_vazios (#N/D): 3650

In [65]:
# Verificando se as datas estão corretas utilizando o datetime que vai converter texto em data  caso esteja
# E utilizando o isna() para contar as falhas,  e o errors="coerce" para transformar um vaalor invalido em vazio

df_data_correta = pd.to_datetime(df["DATA"], format= "%d/%m/%Y",errors="coerce")

df_data_correta.isna().sum()

np.int64(0)

# Limpeza de Dados

In [66]:
# Criando uma cópia dos Dados para uma futura comparação mantendo o Dado original intacto, e fazer a limpeza toda nessa cópia
# Uma vez que já se sabe o que vai ser Limpo.

df_Limpeza_Dados = df.copy()
df

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [ ]:
# Tratando Colunas Vazias eliminando elas

df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])

df

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

In [ ]:
# Tratando Produtos Nulos trabalhando encima da cópia utilizando o replace para trocar o texto #N/D por Produto Vazio,
#  e o isnull pra confirmar se tudo ta 100% sem nulos e conta-los com sum()

df_Limpeza_Dados["PR_CAT"] = df_Limpeza_Dados["PR_CAT"].replace("#N/D", "Sem Categoria")

df_Limpeza_Dados.isnull().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [ ]:
# Eliminando as Duplicadas utilizando o len que vai me contar quantas linhas tem duplicadas antes de ser removida guardando pra ser comparada depois 
# Enquanto isso o drop_duplicate vai limpando as linhas repetidas mantendo a ocorrência inicial ou seja a primeira linha de cada uma 
# E foi feita uma subtração de quantas linhas sairam em ( qtd_linhas_antes-len(df_limpeza_Dados) )

qtd_linhas_antes  = len(df_Limpeza_Dados)
print("Linhas_Iniciais",len(df_Limpeza_Dados))

df_Limpeza_Dados = df_Limpeza_Dados.drop_duplicates()
print("Linhas_Duplicadas: ",qtd_linhas_antes-len(df_Limpeza_Dados))

Linhas_Iniciais 733447
Linhas_Duplicadas:  0